name: Build

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
      - '!dist'
  pull_request:
    types: [opened, reopened, synchronized]
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install browserify babelify @babel/core @babel/preset-env core-js@3 tinyify html-minifier postcss cssnano gh-pages octokit
      - name: Build
        run: node .github/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
