name: Deploy

on:
  push:
    branches:
      - dist

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare website
        run: find . -maxdepth 1 -type d -path "./*" -not -name .git -not -name main -exed cp -R {} main/{} \;
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install gh-pages
      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d main -u "github-actions <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
